spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 123456
    url: jdbc:mysql://47.108.252.146:3306/data_factory?serverTimezone=UTC

  web:
    resources:
      static-locations:
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
